### ISSUE TITLE
does it works with graphite

### ISSUE THREAD

**Issue by aleita** [mtanda/grafana-histogram-panel#14] opened 2016-05-13 14:04 UTC
Hi,

I would like to make an histrogram over data stored into graphite.
the panel remains white. In the upper left corner there is  a red triangle.
It says 

"undefined is not an object(evaluating '$q.when')"

any hint

thanks

Ale

**Comment by mtanda** [comment] 2016-05-13 15:44
What version Grafana use?
Do you use package? Or build from source?

This panel should work with Graphite or other time series data sources.
But I only use this with Prometheus, so I don't test the panel well...

**Comment by aleita** [comment] 2016-05-14 04:31
Grafana 3.0.0 from build

this is the time serie I would like to make an histogram for

<img width="1344" alt="screen shot 2016-05-14 at 06 26 47" src="https://cloud.githubusercontent.com/assets/6066940/15266186/f03ba4aa-199c-11e6-929c-6d66a115cff5.png">

but the same serie with histogram does not work

<img width="1343" alt="screen shot 2016-05-14 at 06 29 48" src="https://cloud.githubusercontent.com/assets/6066940/15266202/561f6770-199d-11e6-8847-ca1b64f67998.png">

is it correct how I'm trying to use it ?

thanks in advance

Ale

**Comment by mtanda** [comment] 2016-05-14 04:52
Yes, it is correct.

I also use Grafana, build from source.
I specify the path of "dist", not "src" in config file.
I use Mac and Google Chrome.

If you tell me the commit hash of your Grafana build, I'll try to replicate :-)

**Comment by mtanda** [comment] 2016-05-14 14:06
Hi, I try to replicate issue by using Graphite in my env.
I don't install Graphite locally, so I use play.grafana.org site Graphite by Grafana proxy mode.

![graphite](https://cloud.githubusercontent.com/assets/224552/15268847/c06df59e-1a27-11e6-8cb3-3ddf0f366260.png)
(specify "http://play.grafana.org/api/datasources/proxy/1/")

and then, I set query like this.
![graphite_histogram](https://cloud.githubusercontent.com/assets/224552/15268864/329b6818-1a28-11e6-8777-b82fd5890a31.png)

The histogram panel works.

The git commit hash of Grafana is https://github.com/grafana/grafana/commit/7bc15ec6c18193f1e6ea3a71437812aa6ee7ec20 .

**Comment by aleita** [comment] 2016-05-14 14:57
first of all thanks for answering.

tha same source does not work for me

root@grafana:~# dpkg -l | grep grafana
ii  grafana                        3.0.1                     amd64        Grafana
root@grafana:~# 

I suppose tha plugin is corrected loaded.
How could I debug this issue ?

<img width="1494" alt="screen shot 2016-05-14 at 16 54 59" src="https://cloud.githubusercontent.com/assets/6066940/15269093/c597c550-19f4-11e6-8c7c-fde0892b8c5e.png">

**Comment by mtanda** [comment] 2016-05-14 16:08
Your environment might be Ubuntu.
And the Grafana is installed by deb package. (download from http://grafana.org/download/builds ?)

Currently I don't have idea how you can resolve issue.
You use Ubuntu and you use deb package, I use Mac and I use local build Grafana, these are difference of our environment.
I'll try to replicate your issue on Ubuntu with package installed Grafana.

I also get bug report of this panel, they also use package version. https://github.com/mtanda/grafana-histogram-panel/issues/7
There are difference between package and local build.
I'm not sure but the difference could cause your reported error.

If you have experience of building from source, please try it.
It's great helpful :-)
http://docs.grafana.org/project/building_from_source/

**Comment by mtanda** [comment] 2016-05-14 16:14
The error message might be caused by this change https://github.com/mtanda/grafana-histogram-panel/pull/13 .
It is only place, I use "$q.when".

I don't test this change with package installed Grafana, I test only Homebrew installed Grafana.
I should check package installed Grafana.
Sorry for inconvenience.

**Comment by mtanda** [comment] 2016-05-15 02:21
@aleita I replicate your issue on Ubuntu.
And I fix it by this  PR. Please renew panel source and test it.
https://github.com/mtanda/grafana-histogram-panel/pull/15

**Comment by aleita** [comment] 2016-05-16 09:08
Yesterday I was able to create some histogram
but today I'm facing a new issue.

When I add panel, selecting Histogram, It seems to work.
If I reload the page, the Histogram panal remains white
![screen shot 2016-05-16 at 11 08 30](https://cloud.githubusercontent.com/assets/6066940/15285301/8ce564f2-1b56-11e6-853b-b7f5af29b077.png)

**Comment by mtanda** [comment] 2016-05-16 09:30
Oh, the "white out" is occurred every time?
Reload means "refresh button of Grafana" or "browser reload button"?

**Comment by Bellovitello** [comment] 2016-05-16 12:24
I have a similar problem.In my setup I have two dashboards:
Dashboard 1: with two histograms
![dashboard1](https://cloud.githubusercontent.com/assets/2598458/15288970/2506b3cc-1b6f-11e6-8b3a-eea891b413f5.png)

Dashboard 2: with a graph panel and an histogram panel
![dashboard2](https://cloud.githubusercontent.com/assets/2598458/15288980/45d73bee-1b6f-11e6-954e-82b09414ed11.png)

It seems all right, but if I open a new browser and I load first Dashboard 2 the result is:
![bug](https://cloud.githubusercontent.com/assets/2598458/15289078/f9ce9a3e-1b6f-11e6-8fc0-7b8405cff80a.png)

As you can see there's an empty histogram and no errors in my browser console. Now if I navigate to Dashboard 1 histograms don't appear also here. After this moment no other histogram will be loaded until I force a page reload.

It seems that your plugin needs to be loaded first and if not it stop working.

I hope this can be helpful.
Thanks

**Comment by aleita** [comment] 2016-05-16 12:57
I'm encountering this issue on both cases "refresh button of Grafana" and "browser reload button".

**Comment by mtanda** [comment] 2016-05-16 13:16
@Bellovitello Thanks for sharing reproduce step!
I succeed to replicate the issue.
![histogram_blackout](https://cloud.githubusercontent.com/assets/224552/15290472/939e82bc-1bb3-11e6-9d50-7f9ad27e74c7.png)

@aleita I got it. I'll investigate the bug.

**Comment by mtanda** [comment] 2016-05-16 14:43
When I change base class to MetricsPanelCtrl, panel is appeard.

Finally, I give up to reuse GraphCtrl code.
https://github.com/mtanda/grafana-histogram-panel/pull/16

**Comment by aleita** [comment] 2016-05-18 08:41
it works for me

**Comment by mtanda** [comment] 2016-05-18 08:45
Thanks for testing 👍 
I close this issue.

**Closed as completed by mtanda** 2016-05-18 08:45 UTC
